In [24]:
import pandas as pd
import numpy as np


In [4]:
datos = pd.read_csv(r'C:\Users\david\OneDrive\Desktop\Archivos Bioseñales\datos.csv')

In [ ]:
print(datos)

In [ ]:
a = np.array([3.1, 1, -0.5, -3.2, 6])
b = np.array([1, 3, 2.2, 5.1, 1])

In [12]:
producto_escalar = np.dot(a, b)
print(producto_escalar)

-5.320000000000002


¿Qué se debe realizar para poder multiplicarlos?


Ambos vectores deben tener:

-La misma dimensión

-El mismo número de elementos

In [13]:
producto_punto_a_punto = a * b
print(producto_punto_a_punto)

[  3.1    3.    -1.1  -16.32   6.  ]


In [14]:
A = np.array([
    [2, -1, -3],
    [4, 1.5, -2.5],
    [7.3, -0.9, 0.2]
])

print("Matriz A:")
print(A)

Matriz A:
[[ 2.  -1.  -3. ]
 [ 4.   1.5 -2.5]
 [ 7.3 -0.9  0.2]]


In [15]:
AT = A.T

print("Transpuesta de A:")
print(AT)

Transpuesta de A:
[[ 2.   4.   7.3]
 [-1.   1.5 -0.9]
 [-3.  -2.5  0.2]]


np.ones()

Crea una matriz llena de unos.

In [16]:
matriz_unos = np.ones((3,3))
print("Matriz de unos:")
print(matriz_unos)

Matriz de unos:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


np.round()

Redondea valores al número de decimales que indiquemos.

In [ ]:
redondeada = np.round(A, 0)  # 0 decimales
print("Matriz redondeada:")
print(redondeada)

Matriz redondeada:
[[ 2. -1. -3.]
 [ 4.  2. -2.]
 [ 7. -1.  0.]]


np.ceil()

Redondea hacia arriba (techo).

In [19]:
ceil_A = np.ceil(A)
print("Matriz con ceil:")
print(ceil_A)

Matriz con ceil:
[[ 2. -1. -3.]
 [ 4.  2. -2.]
 [ 8. -0.  1.]]


np.floor()

Redondea hacia abajo (piso).

In [20]:
floor_A = np.floor(A)
print("Matriz con floor:")
print(floor_A)

Matriz con floor:
[[ 2. -1. -3.]
 [ 4.  1. -3.]
 [ 7. -1.  0.]]


In [21]:
valor = A[0, 2]
print("Valor primera fila, tercera columna:", valor)

Valor primera fila, tercera columna: -3.0


In [22]:
segunda_fila = A[1, :]
print("Segunda fila:")
print(segunda_fila)

Segunda fila:
[ 4.   1.5 -2.5]


El comando es:

.shape

In [23]:
dimensiones = A.shape
print("Dimensiones de A:", dimensiones)

Dimensiones de A: (3, 3)
